// <auto-generated />
using Acfunlivedb.NET.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Acfunlivedb.NET.Migrations
{
    [DbContext(typeof(AcfunlivedbDbContext))]
    [Migration("20230411173225_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("Acfunlivedb.NET.DAL.Entity.Live", b =>
                {
                    b.Property<string>("liveId")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("startTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("streamName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("uid")
                        .HasColumnType("INTEGER");

                    b.HasKey("liveId");

                    b.HasIndex("startTime");

                    b.HasIndex("uid");

                    b.ToTable("Lives");
                });
#pragma warning restore 612, 618
        }
    }
}
